### ISSUE TITLE
Incorrect reading of UART data

### ISSUE THREAD

**Issue by branda92** [Jorre05/micronova#3]
HI,
first of all thank you for your project, it is really useful and functional for those who have a pellet stove with Micronova board.

I built the PCB designed by Filibertc, and I think it's ok. However, I cannot read the UART data correctly. It seems that the data is being read, but incorrectly. I think it depends on wrong UART addresses, but I'm not at all competent on this topic.
Do you think there is a solution to fix the problem?
My Micronova board is a C023_9 from what I've been able to read.
I attach a screenshot of what HA is detecting.

Thanks in advance for the answer.

Branda92
![Screenshot 2023-11-26 alle 18 59 49](https://github.com/Jorre05/micronova/assets/56030046/b807f645-5287-4dc5-8e28-e0bf5385b61b)

**Comment by Jorre05** [comment]
Sorry for my late reply. It looks like your stove needs more time to reply. You can increase the reply delay like this:
```yaml
micronova:
  serial_reply_delay: 120ms
```

**Comment by Jorre05** [comment]
Ow, now I see. I've been in contact with you on Discord.

**Comment by branda92** [comment]
Hi, we've already spoken on discord and I've already tried this solution, but it still doesn't work. It looks like my card is sending signals that it shouldn't.

In the next 2 weeks I try to connect directly with the serial behind the stove, hoping to have a more direct connection.

I will update in case of a positive outcome.

**Comment by tomdudu38** [comment]
hi.
i have the same logs.i tryied serial_reply_delay but:

[serial_reply_delay] is an invalid option for [micronova]. Please check the indentation.

micronova:
  enable_rx_pin: "GPIO25"
  update_interval: 20s
  serial_reply_delay: 100ms

**Comment by Jorre05** [comment]
The serial_reply_delay parameter is not in the ESPHome component (yet). You can use this repo in your config.

```yaml
external_components:
    - source: github://Jorre05/micronova
       components: [ micronova ]
```

**Comment by tomdudu38** [comment]
i'll try thanks you
