### ISSUE TITLE
Stove pressure, set stove temp, set stove pover?

### ISSUE THREAD

**Issue by jeng37** [Jorre05/micronova#9]
Various variables don't work for me.

1. Stove pressure
2. Set stove temperature
3. Set stove power level

Everything else works.
Stove is an Extraflame Diadema Idro.

What can I do?
![micronova](https://github.com/user-attachments/assets/7740b2e3-cae9-43f8-a1ce-bafe053e7e09)

Log:
[logs_micronova_run.txt](https://github.com/user-attachments/files/16193904/logs_micronova_run.txt)

Oh yeah, I forgot to mention that I use this adapter.
![wiring](https://github.com/user-attachments/assets/f09dd172-8add-4655-a5c4-c0303be7a19b)

**Comment by Jorre05** [comment]
Sorry for my late reply.
I think the default "memory location" and "memory address" that I use are not compatible with your stove. As I only have one stove myself I'm unable to discover the correct parameters for you specific type. I'd suggest that you ask the discord channel for help on your specific type.

**Comment by jeng37** [comment]
Ok, thx!
